### ISSUE TITLE
Not able to animate using traja.plotting.animate

### ISSUE THREAD

**Issue by dhivya-jayaraman** [traja-team/traja#20]
```
traja.plotting.animate(trj: TrajaDataFrame, polar = True, save = False)

Error:
File "<ipython-input-179-b9f35fc742bf>", line 2
    gsts_ais_grp.traja.plotting.animate(trj: TrajaDataFrame, polar = True, save = False)
                                           ^
SyntaxError: invalid syntax
```

I'm trying to animate a trajectory by using plotting.animate(). I'm not sure if trj is the dataframe or should it be like  gsts_ais_grp.traja.plotting.animate(trj: TrajaDataFrame, polar = True, save = False). Either way I'm getting syntax error. Please help me with this. 
Thanks in advance!

**Comment by justinshenk** [comment]
The ability to call all methods through the traja accessor (df.traja...)
was not previously possible. This feature has just been added to
traja==0.2.0. Please upgrade to the new version and try again (ex:
gsts_ais_grp.traja.animate()). Let me know if you have any further issues.

**Comment by dhivya-jayaraman** [comment]
```
pip install -I traja==0.2.0
Collecting traja==0.2.0
  ERROR: Could not find a version that satisfies the requirement traja==0.2.0 (from versions: 0.0.1, 0.0.2a1, 0.0.2a2, 0.0.2a4, 0.0.4, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.14, 0.0.17, 0.0.20, 0.1.0, 0.1.1.dev0, 0.1.1.dev1, 0.1.1, 0.1.1.post0, 0.1.2.dev0, 0.1.2, 0.1.2.post0, 0.1.2.post2, 0.1.2.post4, 0.1.3.dev3, 0.1.4, 0.1.7, 0.1.8)
ERROR: No matching distribution found for traja==0.2.0
```

I'm not able to upgrade the version to 0.2.0. Tried using both pip and conda. It says that the specified version is not found.

**Comment by dhivya-jayaraman** [comment]
```
--------------------------------------------------------------------------
AttributeError                           Traceback (most recent call last)
<ipython-input-26-f81b91719e6f> in <module>
----> 1 gsts.traja.animate()

/opt/anaconda3/lib/python3.7/site-packages/traja/accessor.py in method(*args, **kwargs)
    272         def method(*args, **kwargs):
    273             if name in traja.plotting.__all__:
--> 274                 return getattr(traja.plotting, name)(self._obj, *args, **kwargs)
    275             elif name in traja.trajectory.__all__:
    276                 return getattr(traja.plotting, name)(self._obj, *args, **kwargs)

/opt/anaconda3/lib/python3.7/site-packages/traja/plotting.py in animate(trj, polar, save)
   1285         xlim=xlim,
   1286         ylim=ylim,
-> 1287         ylabel=trj.spatial_units or "m",
   1288         xlabel=trj.spatial_units or "m",
   1289         aspect="equal",

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5177             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5178                 return self[name]
-> 5179             return object.__getattribute__(self, name)
   5180 
   5181     def __setattr__(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'spatial_units'
```

Hello Justin, sorry to keep bothering you. I'm not sure if I'm doing something wrong here. I have dataframe of id, lat, lon, time (in seconds) and distance (using traja.calc_displacement()). I'm trying to call the animate() function with traja version 0.2.0. It throws an attribute error.

**Comment by justinshenk** [comment]
Sorry, the error you received was due to Traja expecting a TrajaDataFrame
rather than pandas DataFrame. This has now been fixed in traja==0.2.1.

Let me know if you have any further issues.

**Comment by dhivya-jayaraman** [comment]
I'm still getting the same error with pandas dataframe so I converted to traja dataframe which got it to work but I'm not sure it is animating. It just has 1 frame. The trajectory of the item which plotted using TrajaCollection() is shown in the figure below.
![Screen Shot 2020-01-15 at 10 40 46 AM](https://user-images.githubusercontent.com/23284270/72442794-8fbd1b00-3783-11ea-88b0-5c28e9dca160.png)

When I try to animate the same but I get this static image with just frame 0 shown below.
![Screen Shot 2020-01-15 at 10 40 56 AM](https://user-images.githubusercontent.com/23284270/72442956-d90d6a80-3783-11ea-8295-d08a23457702.png)

**Comment by justinshenk** [comment]
Thanks for bringing this to my attention. The frozen screen issue is
hopefully fixed in v0.2.2, along with the support for the pandas DataFrame.

Now this should work:
```
df = pd.DataFrame({"x":[1,10,20,5]*10,"y":[2,30,40,20]*10})
df.traja.animate()
```

Can you share a minimal amount of data so I can test it? Also via email is
find (shenkjustin@gmail.com).

**Comment by justinshenk** [comment]
Closing due to inactivity
